version: "3.3"
services:
  bulldozer_agent:
    image: bulldozer_agent:0.0.1
    restart: always
    volumes:
      - ./agent.json:/app/agent.json
      - ./ip2region.db:/app/ip2region.db
    network_mode: host
